apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: puzzle-assembler
    factory: puzzle
  name: puzzle-assembler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzle-assembler
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: puzzle-assembler
        factory: puzzle
    spec:
      containers:
        - image: puzzle-assembler:1.1-SNAPSHOT
          imagePullPolicy: Never
          name: puzzle-assembler
          resources:
            limits:
              cpu: "1000m"
              memory: "700Mi"
          ports:
            - containerPort: 8080
          args:
            - --spring.config.location=/config/application.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 10
          volumeMounts:
            - name: app-config
              mountPath: /config
      volumes:
        - name: app-config
          configMap:
            name: puzzle-assembler-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: puzzle-assembler-config
  namespace: default
data:
  application.yaml: |
    server.port: 8080
    app:
      kafka:
        bootstrap: kafka-service-internal:9092
        newTaskTopic: puzzleTopics
