apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: puzzle-api
  name: puzzle-api
  namespace: default
spec:
  containers:
  - image: puzzle-api:1.0-SNAPSHOT
    name: puzzle-api
    resources: 
      limits:
        cpu: "200m"
        memory: "1G"
    imagePullPolicy: Never
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
